// Package fingerprint generates cryptographically random per-startup identifiers
// so that no two Tacoma deployments share static fingerprints.
package fingerprint

import (
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"math/big"
	"time"
)

// FP holds all randomized values generated at daemon startup.
// Every value is derived from crypto/rand — never math/rand or time.Now().
type FP struct {
	// Redis
	RedisRunID        string // 40 lowercase hex chars
	RedisMasterReplID string // 40 lowercase hex chars
	RedisProcessID    int
	RedisSaveEpoch    int64 // fixed last-save timestamp (startup - random offset)

	// MySQL
	MySQLStartupTime time.Time // used to compute Uptime

	// PostgreSQL — per-connection values generated by PGSalt/PGPID helpers

	// MongoDB
	MongoClusterID string // UUID v4
	MongoNodeID    string // UUID v4
	MongoPID       int

	// Elasticsearch / CouchDB (shared HTTP services)
	ESNodeUUID   string // 22-char base62-like (matches ES node ID format)
	ESBuildHash  string // 40 lowercase hex chars
	ESHostname   string
	ESPID        int
	ESMACAddress string

	StartTime time.Time
}

// New generates a fresh FP using crypto/rand. Panics on entropy failure (unrecoverable).
func New(esHostname string) *FP {
	fp := &FP{
		StartTime:        time.Now(),
		MySQLStartupTime: time.Now(),
		ESHostname:       esHostname,
	}

	fp.RedisRunID = randHex(20)
	fp.RedisMasterReplID = randHex(20)
	fp.RedisProcessID = randIntRange(1000, 65535)
	fp.RedisSaveEpoch = fp.StartTime.Unix() - int64(randIntRange(300, 86400))

	fp.MongoClusterID = randUUIDv4()
	fp.MongoNodeID = randUUIDv4()
	fp.MongoPID = randIntRange(1000, 65535)

	fp.ESNodeUUID = randESNodeID()
	fp.ESBuildHash = randHex(20)
	fp.ESPID = randIntRange(1000, 65535)
	fp.ESMACAddress = randMAC()

	if fp.ESHostname == "" {
		fp.ESHostname = randHostname()
	}

	return fp
}

// PGSalt generates a cryptographically random 4-byte PostgreSQL MD5 salt.
func PGSalt() [4]byte {
	var b [4]byte
	mustRead(b[:])
	return b
}

// PGPID generates a random backend PID in a realistic range.
func PGPID() int32 {
	return int32(randIntRange(2000, 65534))
}

// MySQLScramble generates a cryptographically random 20-byte MySQL auth challenge.
// Real MySQL uses 20 bytes split as auth-plugin-data-part-1 (8) + part-2 (12).
// All bytes are in [1, 254] per the MySQL protocol spec (no null bytes).
func MySQLScramble() [20]byte {
	var b [20]byte
	for i := range b {
		for {
			var buf [1]byte
			mustRead(buf[:])
			v := buf[0]
			if v != 0 {
				b[i] = v
				break
			}
		}
	}
	return b
}

// MySQLConnID returns a random connection ID in the range MySQL servers use.
func MySQLConnID() uint32 {
	return uint32(randIntRange(1, 1<<24-1))
}

// randHex returns n cryptographically random bytes encoded as lowercase hex (2n chars).
func randHex(n int) string {
	b := make([]byte, n)
	mustRead(b)
	return hex.EncodeToString(b)
}

// randUUIDv4 returns a random UUID v4 string.
func randUUIDv4() string {
	var b [16]byte
	mustRead(b[:])
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// randESNodeID returns a 22-character random string that matches
// Elasticsearch's base64url-encoded node ID format.
func randESNodeID() string {
	const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
	out := make([]byte, 22)
	for i := range out {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(chars))))
		if err != nil {
			panic("crypto/rand failed: " + err.Error())
		}
		out[i] = chars[n.Int64()]
	}
	return string(out)
}

// randMAC returns a random unicast locally-administered MAC address.
func randMAC() string {
	var b [6]byte
	mustRead(b[:])
	b[0] = (b[0] & 0xfe) | 0x02 // locally administered, unicast
	return fmt.Sprintf("%02x:%02x:%02x:%02x:%02x:%02x",
		b[0], b[1], b[2], b[3], b[4], b[5])
}

// randHostname returns a plausible short hostname.
func randHostname() string {
	prefixes := []string{"node", "srv", "prod", "app", "db", "es", "cache"}
	suffix := randIntRange(1, 99)
	idx := randIntRange(0, len(prefixes)-1)
	return fmt.Sprintf("%s%02d", prefixes[idx], suffix)
}

// randIntRange returns a cryptographically random int in [lo, hi] inclusive.
func randIntRange(lo, hi int) int {
	if lo >= hi {
		return lo
	}
	n, err := rand.Int(rand.Reader, big.NewInt(int64(hi-lo+1)))
	if err != nil {
		panic("crypto/rand failed: " + err.Error())
	}
	return lo + int(n.Int64())
}

func mustRead(b []byte) {
	if _, err := rand.Read(b); err != nil {
		panic("crypto/rand failed: " + err.Error())
	}
}

// UptimeSeconds returns the wall-clock seconds since StartTime.
func (fp *FP) UptimeSeconds() int64 {
	return int64(time.Since(fp.StartTime).Seconds())
}

// randUint32 returns a cryptographically random uint32 (used for MySQL cancel key etc.)
func RandUint32() uint32 {
	var b [4]byte
	mustRead(b[:])
	return binary.LittleEndian.Uint32(b[:])
}
